from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         views.IndexView.as_view(),
         name='index'),
    path('about/',
         views.AboutPageView.as_view(),
         name='about'),
    path('profile/<str:username>/',
         views.ProfilePageView.as_view(),
         name='profile'),
    path('posts/<int:post_id>/',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('posts/create/',
         views.CreatePostView.as_view(),
         name='post_create'),
    path('posts/<int:post_id>/review/',
         views.AddReviewView.as_view(),
         name='add_review'),
    path('posts/<int:post_id>/delete/',
         views.DeletePostView.as_view(),
         name='post_delete'),
    path('posts/<int:post_id>/edit/',
         views.EditPostView.as_view(),
         name='edit_post'),
    path('playlists/',
         views.PlayListView.as_view(),
         name='playlists'),
    path('playlists/create/',
         views.CreatePlayListView.as_view(),
         name='playlist_create'),
    path('playlist/<int:playlist_id>/detail/',
         views.PlayListDetailView.as_view(),
         name='playlist_detail'),
    path('playlist/<int:playlist_id>/delete/',
         views.DeletePlaylistView.as_view(),
         name='playlist_delete'),
    path('favorites_add/<int:post_id>/',
         views.AddToPlaylistView.as_view(),
         name='add_to_playlist'),
    path('playlist/<int:playlist_id>/<int:post_id>/',
         views.PostDisableView.as_view(),
         name='delete_from_playlist'),
]
