# Generated by Django 3.2.16 on 2023-11-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='pub_date',
        ),
    ]
