# Generated by Django 3.2.16 on 2023-11-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название песни'),
        ),
    ]
